export const squadTypes = [
  {
    id: 1,
    type: "ANY_SQUAD",
    name: "Any Squad",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "chapter",
  },
  {
    id: 2,
    type: "PURGE_DOCTOR",
    name: "Purge Doctor",
    img: "images/factions/chapter/units/purge_doctor.png",
    background: "images/factions/chapter/units/purge_doctor_Defense.png",
    cardCount: 1,
    isElite: true,
    isCavalery: false,
    count: 0,
    faction: "chapter",
  },
  {
    id: 3,
    type: "PILGRIM",
    name: "Pilgrim",
    img: "images/factions/chapter/units/pilgrim.png",
    background: "images/factions/chapter/units/pilgrim_run.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "chapter",
  },
  {
    id: 4,
    type: "HOLY_KNIGHT",
    name: "Holy Knight",
    img: "images/factions/chapter/units/holy_knight_1.png",
    background: "images/factions/chapter/units/holy_knight_1_upgraded.png",
    cardCount: 3,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "chapter",
  },
  {
    id: 5,
    type: "RANGER",
    name: "Ranger",
    img: "images/factions/chapter/units/ranger.png",
    background: "images/factions/chapter/units/ranger_aim.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "chapter",
  },
  {
    id: 6,
    type: "ANGEL_OF_DEATH",
    name: "Angel of Death",
    img: "images/factions/chapter/units/angel_of_death.png",
    background: "images/factions/chapter/units/angel_of_death_flight.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "chapter",
  },
  {
    id: 7,
    type: "INFINITY_ANGEL",
    name: "Infinity Angel",
    img: "images/factions/chapter/units/infinity_angel.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 8,
    type: "SOURCE_BLADE",
    name: "Source Blade",
    img: "images/factions/chapter/units/source_blade.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 9,
    type: "STORM_BRINGER",
    name: "Storm Bringer",
    img: "images/factions/chapter/units/storm_bringer.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 10,
    type: "STREAM_GUARD",
    name: "Stream Guard",
    img: "images/factions/chapter/units/stream_guard_1.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 11,
    type: "STREAM_SURFER",
    name: "Stream Surfer",
    img: "images/factions/chapter/units/stream_surfer.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 12,
    type: "SON_OF_KHYBER",
    name: "Son of Khyber",
    img: "images/factions/demon/units/son_of_khyber.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "demon",
  },
  {
    id: 13,
    type: "MASTER_OF_ELEMENTS",
    name: "Master of Elements",
    img: "images/factions/demon/units/master_of_elements.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "demon",
  },
  {
    id: 14,
    type: "GOREHOUND",
    name: "Gorehound",
    img: "images/factions/demon/units/gorehound_1.png",
    cardCount: 2,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "demon",
  },
  {
    id: 15,
    type: "DARK_SCHOLAR",
    name: "Dark Scholar",
    img: "images/factions/demon/units/dark_scholar_1.png",
    cardCount: 2,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "demon",
  },
  {
    id: 16,
    type: "BLOODSMITH",
    name: "Bloodsmith",
    img: "images/factions/demon/units/bloodsmith.png",
    cardCount: 1,
    isElite: true,
    isCavalery: false,
    count: 0,
    faction: "demon",
  },
  {
    id: 17,
    type: "AVENGER",
    name: "Avenger",
    img: "images/factions/dvergar/units/avenger.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "dvergar",
  },
  {
    id: 18,
    type: "FLAME_KEEPER",
    name: "Flame Keeper",
    img: "images/factions/dvergar/units/flame_keeper.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "dvergar",
  },
  {
    id: 19,
    type: "ENKINDLED",
    name: "Enkindled",
    img: "images/factions/dvergar/units/enkindled.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "dvergar",
  },
  {
    id: 20,
    type: "UNBROKEN",
    name: "Unbroken",
    img: "images/factions/dvergar/units/unbroken_1.png",
    cardCount: 2,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "dvergar",
  },
  {
    id: 21,
    type: "GYROBOT",
    name: "Gyrobot",
    img: "images/factions/dvergar/units/gyrobot.png",
    cardCount: 1,
    isElite: true,
    isCavalery: false,
    count: 0,
    faction: "dvergar",
  },
  {
    id: 22,
    type: "SHATTERER",
    name: "Shatterer",
    img: "images/factions/faceless/units/shatterer.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "faceless",
  },
  {
    id: 23,
    type: "HARVESTER",
    name: "Harvester",
    img: "images/factions/faceless/units/harvester.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "faceless",
  },
  {
    id: 24,
    type: "BLADEBREEDER",
    name: "Bladebreeder",
    img: "images/factions/faceless/units/bladebreeder.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "faceless",
  },
  {
    id: 25,
    type: "BERSERKER",
    name: "Berserker",
    img: "images/factions/faceless/units/berserker_1.png",
    cardCount: 2,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "faceless",
  },
  {
    id: 26,
    type: "FLESHRIPPER",
    name: "Fleshripper",
    img: "images/factions/faceless/units/fleshripper.png",
    cardCount: 1,
    isElite: true,
    isCavalery: false,
    count: 0,
    faction: "faceless",
  },
  {
    id: 27,
    type: "ORACLE_OF_WRATH",
    name: "Oracle of Wrather",
    img: "images/factions/reborn/units/oracle_of_wrath.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "reborn",
  },
  {
    id: 28,
    type: "BLIGHT_STEED",
    name: "Blight Steed",
    img: "images/factions/reborn/units/blight_steed.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "reborn",
  },
  {
    id: 29,
    type: "WARBEAST",
    name: "Warbeast",
    img: "images/factions/reborn/units/warbeast.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "reborn",
  },
  {
    id: 30,
    type: "WYRM",
    name: "Wyrm",
    img: "images/factions/reborn/units/wyrm.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "reborn",
  },
  {
    id: 31,
    type: "TREEMAID",
    name: "Treemaid",
    img: "images/factions/reborn/units/treemaid.png",
    cardCount: 1,
    isElite: false,
    isCavalery: false,
    count: 0,
    faction: "reborn",
  },
  {
    id: 32,
    type: "ANCIENT_GUARD",
    name: "Ancient Guard",
    img: "images/factions/reborn/units/ancient_guard.png",
    cardCount: 1,
    isElite: true,
    isCavalery: false,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 33,
    type: "ANATHEMA",
    name: "Anathema",
    img: "images/factions/faceless/units/anathema.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "faceless",
  },
  {
    id: 34,
    type: "HOLY_RIDERS",
    name: "Holy Riders",
    img: "images/factions/chapter/units/holy_riders.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "chapter",
  },
  {
    id: 35,
    type: "SUCCUBUS",
    name: "Succubus",
    img: "images/factions/demon/units/succubus.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "demon",
  },
  {
    id: 36,
    type: "DRILLERS",
    name: "Drillers",
    img: "images/factions/dvergar/units/drillers.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "dvergar",
  },
  {
    id: 37,
    type: "FOREST_WRAITH",
    name: "Forest Wraith",
    img: "images/factions/reborn/units/forest_wraith.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "reborn",
  },
  {
    id: 38,
    type: "JUMPSUIT",
    name: "Jumpsuit",
    img: "images/factions/rhazack/units/jumpsuit.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "rhazack",
  },
  {
    id: 39,
    type: "PRIME_SHADOW",
    name: "Prime Shadow",
    img: "images/factions/darkness/units/prime_shadow.png",
    cardCount: 1,
    isElite: false,
    isCavalery: true,
    count: 0,
    faction: "darkness",
  },
];
